### ISSUE TITLE
Bump to typst 0.11

### ISSUE THREAD

**Issue by DrLoiseau** [havarddj/typst-preview.el#1]
Hey, 
I'd love to try this package in emacs, but it seems it is currently not compatible with typst v0.11. I had this error in ws-typst-server when trying it : 
error: expected semicolon or line break
```
    ┌─ @local/teacher:0.2.0/functions.typ:123:33
    │
123 │             let act_num = context {
    │                                  ^
```
I guess it means typst-preview doesn't know yet about context because my file compiles normally.
Any plans to adapt it ? Or am I wrong and may it be related to my setup ?

**Comment by havarddj** [comment]
Interesting! Contexts seem to work in my preview after upgrading typst-preview to the latest version.

 Have you checked if you have the latest typst-preview binary from https://github.com/Enter-tainer/typst-preview/releases/ (v0.11.1)? Apparently context support [was added in version 0.11](https://github.com/Enter-tainer/typst-preview/issues/272).

If this doesn't work, send me a minimal example that reproduces the error, and I'll check.

**Comment by DrLoiseau** [comment]
Woups I had forgotten it was based on vscode typst-preview. I updated it and it works fine ! Amazing !
