### ISSUE TITLE
Typst-preview with eaf-browser or other emacs browser without xwidget

### ISSUE THREAD

**Issue by DrLoiseau** [havarddj/typst-preview.el#3]
Hi,

I wondered if there was to set typst-preview-browser to an emacs browser.

I've been able to use typst-preview with konqueror, and it's awesome !
Now i'm trying to use it directly inside emacs, but I don't have xwidget support. I came across the eaf browser : https://github.com/emacs-eaf/eaf-browser/tree/master and I thought I could run typst-preview inside it. How would I achieve it ? I tried to add a hook to setq browse-url-generic-program like advised in the doc, but I don't  know how to pass it a lisp function like eaf-open.

Thanks !

**Comment by havarddj** [comment]
Hi! I have added an option to open in eaf-browser which I _think_ should work. If you could try pull the latest version, run `typst-preview-open-browser`, and report back, that'd be great!

**Comment by DrLoiseau** [comment]
Yes ! It works ! Just set typst-preview-browser to "eaf-browser" and I get the preview in a side by side window when I run typst-preview-mode. That's a great day for typst in emacs !
Thanks a lot

**Comment by havarddj** [comment]
Wonderful! Glad it works.
