### ISSUE TITLE
Support for `#import`ed files?

### ISSUE THREAD

**Issue by m4xxed** [havarddj/typst-preview.el#6]
Hey,

is there any way I can make this preview functionality behave as described:

+ I start `typst-preview-mode` in the main document buffer, e.g. `thesis.typ`
+ The browser opens with the preview.
+ I click on a page that is actually an `#import`ed chapter, e.g. `introduction.typ`
+ The file gets opened in emacs

--- so far all of this works ---

+ `typst-preview-mode` is automatically started in this sub-file but ONLY IF `typst-preview-mode` has already been started in the main buffer (I don't want to just hook it into `typst-ts-mode` because sometimes I want to just use `typst-ts-watch-mode` because it pops up a compilation error which is convenient sometimes)
+ even more awesome if this does not ask me for the master file again :slightly_smiling_face:

This would then enable me to jump to imported files by clicking in the browser, then move within the opened buffer of the imported file and use `send-position` to jump the browser to the right location, which is a workflow I like very much.

**Comment by havarddj** [comment]
I don't see why that shouldn't be possible, I'll have a try later his week.

**Comment by havarddj** [comment]
Hi! I've improved it a fair bit now, and also upgraded the entire code. In particular, now `typst-preview-stop' (hopefully) works, and is run when the buffer is killed. Let me know if you have any feedback, and I'll try to submit it to MELPA sometime soon.

**Comment by m4xxed** [comment]
Just tested it - it works like a charm! Wow!

The only thing missing for me right now is that if I manually open an imported file and enable typst-preview-mode, it asks me for the master file still (as long as I have not set it as a file-local variable before). 

But I guess the master file cannot be automatically detected without considerable effort.

However, the preview works beautifully and I am very happy with it. Makes working with `typst` even more convenient! 

Thank you very much!

**Comment by havarddj** [comment]
Great, glad it works! I don't think I'll make it a goal to automatically detect the master before that file is being previewed, because an included file can have multiple masters. For example, I often include a template file in multiple documents at the same time. However, one idea could be to write a script to be run in your main buffer, which looks at all instances of "include" in that file and records the current file as master in file-local variables in all of the children, unless there is a conflict.
