### ISSUE TITLE
(search-failed "Control plane server listening on:")

### ISSUE THREAD

**Issue by Zjl37** [havarddj/typst-preview.el#7]
Hi, just trying out this and I found `typst-preview-start` won't start with this error:

```elisp
Debugger entered--Lisp error: (search-failed "Control plane server listening on:")
  search-backward("Control plane server listening on:" nil)
  tp--find-server-address("Control plane")
  typst-preview-start()
  typst-preview-mode(toggle)
  funcall-interactively(typst-preview-mode toggle)
  command-execute(typst-preview-mode record)
  #<subr execute-extended-command>(nil "typst-preview-mode" nil)
  ad-Advice-execute-extended-command(#<subr execute-extended-command> nil "typst-preview-mode" nil)
  apply(ad-Advice-execute-extended-command #<subr execute-extended-command> (nil "typst-preview-mode" nil))
  execute-extended-command(nil "typst-preview-mode" nil)
  funcall-interactively(execute-extended-command nil "typst-preview-mode" nil)
  command-execute(execute-extended-command)
```

Then I checked `*ws-typst-server*` buffer, indeed I cannot find "Control plane server listening ", but there are `Control panel server listening on: 127.0.0.1:34819`. By changing `plane` to `panel` in this line I can get everything working:

https://github.com/havarddj/typst-preview.el/blob/b7cbfb9403c445d4d60da97db3c027322cb70e4b/typst-preview.el#L259

Guess this is the output of tinymist changed in recent version. My `tinymist --version`:

```
tinymist 
Build Timestamp:     2024-10-19T17:10:46.837035115Z
Build Git Describe:  v0.12.0
Commit SHA:          4437b3bffb5f01f06bd64e4e424480ba72a88619
Commit Date:         None
Commit Branch:       None
Cargo Target Triple: x86_64-unknown-linux-gnu
Typst Version:       0.12.0
Typst Source:        git+https://github.com/Myriad-Dreamin/typst.git?tag=tinymist-v0.12.0#58426a90a7ef721738a01be09793d33e55eb75a9
```

**Comment by havarddj** [comment]
Hey! Yeah I noticed this too, and found the same fix. First I was thinking of making a PR for tinymist, but then I got distracted thinking I should implement a better method for getting the control host address from the process, instead of just searching the buffer, which might fill slowly. I'll have a think about it, but feel free to make an issue in the tinymist repo, I suspect it's a typo.

**Comment by havarddj** [comment]
I've pushed an update which fixes this now, which should be backwards-compatible.
